version: '3'
services:
  packet-forwarder:
    image: "hummingbirdminer/hnt-pkt-fwd:0.1.0"
        #network_mode: "host"
    logging:
        driver: journald
    privileged: true
    restart: always
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/ttyAMA1:/dev/AMA1"
  helium-miner:
    image: "quay.io/team-helium/miner:latest-arm64"
    privileged: true
    logging:
        driver: journald
    ulimits:
      nofile:
        soft: "64000"
        hard: "64000"
    expose:
      - "4467"
      - "1680"
    ports:
      - "44158:44158/tcp"
    volumes:
      - '/var/run/dbus:/var/run/dbus'
      - '/var/data:/var/data'
      - 'pktfwdr:/var/pktfwd'
      - './config/overlay/docker.config:/opt/miner/releases/2021.09.16.1/sys.config'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'REGION_OVERRIDE=CN470'
        # - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'
  gateway-config:
    image: "hummingbirdiot/gateway-config:0.1.0"
    logging:
        driver: journald
    privileged: true
    ulimits:
      nofile:
        soft: "64000"
        hard: "64000"
    volumes:
      - '/var/run/dbus:/var/run/dbus'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
